releasetools: Fix the size check for AVB images.
When generating full OTAs for AVB-enabled targets, it fails the size
assertion for boot.img.

  ERROR: boot size (31457280) is 100.00% of limit (31457280).

The size assumption is no longer true for AVB-signed images, because
the actual image size should be always identical to the limit.

Bug: 67841177.
(cherry picked from commit 9dd909e6db2bf143dcc9369155389a48a1b427bc)
Change-Id: I9bd432ccd88094628eb71308554839549eccb6d9